TelevisionModelWebApp/Models/BroadcastingModel.cs
using TelevisionModel.Content;
using TelevisionModel.Utils;

namespace TelevisionModelWebApp.Models;

public class BroadcastingModel
{
    public TelevisionChannel Channel { get; set; }
    
    public TechnicalSpecifications Specifications { get; set; }

    public BroadcastingModel(TelevisionChannel channel, TechnicalSpecifications specs)
    {
        Channel = channel;
        Specifications = specs;
    }
}

TelevisionModelWebApp/Models/ErrorViewModel.cs
namespace TelevisionModelWebApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

TelevisionModelWebApp/Models/ExternalDeviceModel.cs
using TelevisionModel.Devices;
using TelevisionModel.Utils;

namespace TelevisionModelWebApp.Models;

public class ExternalDeviceModel
{
    public Device Device { get; private set; }
    
    public TechnicalSpecifications Specifications { get; private set; }

    public ExternalDeviceModel(TechnicalSpecifications specs)
    {
        Device = new Device("None");
        Specifications = specs;
    }

    public ExternalDeviceModel(string deviceName, TechnicalSpecifications specs)
    {
        Device = new Device(deviceName);
        Specifications = specs;
    }
}

TelevisionModelWebApp/Models/StreamingModel.cs
using TelevisionModel.Content;
using TelevisionModel.Utils;

namespace TelevisionModelWebApp.Models;

public class StreamingModel
{
    public TelevisionSeries Series { get; set; }
    
    public TechnicalSpecifications Specifications { get; set; }

    public StreamingModel(TelevisionSeries series, TechnicalSpecifications specs)
    {
        Series = series;
        Specifications = specs;
    }
}

TelevisionModelWebApp/Controllers/TelevisionController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using TelevisionModel;
using TelevisionModel.Devices;
using TelevisionModel.Utils;
using TelevisionModelWebApp.Models;

namespace TelevisionModelWebApp.Controllers;

public class TelevisionController : Controller
{
    private readonly ILogger<TelevisionController> _logger;

    private readonly Television _television;
    
    private readonly RemoteControl _remoteControl;

    public TelevisionController(ILogger<TelevisionController> logger, Television television, RemoteControl remoteControl)
    {
        _logger = logger;
        _television = television;
        _remoteControl = remoteControl;
    }

    public IActionResult TurnOff()
    {
        if (_television.State != States.TurnedOff) _remoteControl.PowerSwitch();
        return View();
    }

    public IActionResult TurnOn()
    {
        _remoteControl.PowerSwitch();
        TempData["PreviousAction"] = "MainMenu";
        return View("MainMenu", _television.Specifications);
    }

    public IActionResult MainMenu()
    {
        _remoteControl.MainMenu();
        return View(_television.Specifications);
    }

    public IActionResult Next()
    {
        _remoteControl.NextChannel();

        if (_television.State == States.TelevisionBroadcasting)
        {
            BroadcastingModel broadcastingModel =
                new BroadcastingModel(_television.CurrentChannelBroadcastingSystem.SelectedChannel,
                    _television.Specifications);
            return View("TelevisionBroadcast", broadcastingModel);
        }
        
        StreamingModel streamingModel =
            new StreamingModel(_television.StreamingService.SelectedSeries, _television.Specifications);
        return View("Streaming", streamingModel);
    }
    
    public IActionResult Previous()
    {
        _remoteControl.PreviousChannel();

        if (_television.State == States.TelevisionBroadcasting)
        {
            BroadcastingModel broadcastingModel =
                new BroadcastingModel(_television.CurrentChannelBroadcastingSystem.SelectedChannel,
                    _television.Specifications);
            return View("TelevisionBroadcast", broadcastingModel);
        }
        
        StreamingModel streamingModel =
            new StreamingModel(_television.StreamingService.SelectedSeries, _television.Specifications);
        return View("Streaming", streamingModel);
    }
    
    [HttpPost]
    public IActionResult EditVolume(string newVolume, string currentView)
    {
        TempData["InfoMessage"] = _remoteControl.EditVolume(Convert.ToDouble(newVolume))?.MessageDescription;
        
        if (currentView == "TelevisionBroadcast")
        {
            BroadcastingModel broadcastingModel =
                new BroadcastingModel(_television.CurrentChannelBroadcastingSystem.SelectedChannel,
                    _television.Specifications);
            return View(currentView, broadcastingModel);
        }

        if (currentView == "Streaming")
        {
            StreamingModel streamingModel =
                new StreamingModel(_television.StreamingService.SelectedSeries, _television.Specifications);
            return View(currentView, streamingModel);
        }

        if (currentView == "Screencast")
        {
            ExternalDeviceModel externalDeviceModel = new ExternalDeviceModel(_television.Specifications);
            return View(currentView, externalDeviceModel);
        }
        
        return View(currentView, _television.Specifications);
    }

    [HttpPost]
    public string Save()
    {
        try
        {
            Saver.SaveToFile(_television);
        }
        catch (Exception e)
        {
            return "Failed to save state";
        }
        
        return "State was successfully saved";
    }
    
    [HttpPost]
    public IActionResult ChangeResolution(int resolutionX, int resolutionY)
    {
        TempData["InfoMessage"] = _remoteControl.ChangeResolution(resolutionX, resolutionY)?.MessageDescription;
        return View("MainMenu", _television.Specifications);
    }
    
    [HttpPost]
    public IActionResult UpdateSoftware(string newVersion)
    {
        TempData["InfoMessage"] = _remoteControl.UpdateSoftware(newVersion)?.MessageDescription;
        return View("MainMenu", _television.Specifications);
    }
    
    public IActionResult TelevisionBroadcast()
    {
        _remoteControl.TelevisionBroadcasting(); 
        BroadcastingModel broadcastingModel =
            new BroadcastingModel(_television.CurrentChannelBroadcastingSystem.SelectedChannel,
                _television.Specifications);
        return View(broadcastingModel);
    }
    
    public IActionResult Streaming()
    {
        _remoteControl.Streaming();
        StreamingModel model =
            new StreamingModel(_television.StreamingService.SelectedSeries, _television.Specifications);
        return View(model);
    }
    
    [HttpGet]
    public IActionResult Screencast()
    {
        ExternalDeviceModel externalDeviceModel = new ExternalDeviceModel(_television.Specifications);
        return View(externalDeviceModel);
    }

    [HttpPost]
    public IActionResult Screencast(string? newDeviceName)
    {
        if (string.IsNullOrEmpty(newDeviceName) || newDeviceName == "none" || newDeviceName == "None")
        {
            TempData["InfoMessage"] = "Cannot connect to such device";
            ExternalDeviceModel externalDevice = new ExternalDeviceModel(_television.Specifications);
            return View(externalDevice);
        }
        ExternalDeviceModel externalDeviceModel = new ExternalDeviceModel(newDeviceName, _television.Specifications);
        _remoteControl.ExternalDeviceScreencast(externalDeviceModel.Device);
        return View(externalDeviceModel);
    }

    public IActionResult Disconnect()
    {
        ExternalDeviceModel externalDeviceModel = new ExternalDeviceModel(_television.Specifications);
        return View("Screencast", externalDeviceModel);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

TelevisionModelWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - TelevisionModelWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/TelevisionModelWebApp.styles.css" asp-append-version="true"/>
</head>
<body>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TelevisionModelWebApp/Views/Television/MainMenu.cshtml
@model TelevisionModel.Utils.TechnicalSpecifications

@{
    ViewData["Title"] = "Main menu";
}

@if (TempData["InfoMessage"] != null)
{
    <div id="alert" class="alert alert-info alert-dismissible alert-fade custom-alert position-fixed" style="top: -10px; right: 10px; z-index: 1050;" role="alert">
        @TempData["InfoMessage"]
        <button type="button" class="close btn btn-close" data-dismiss="alert" aria-label="Close">
        </button>
    </div>
}
else
{
    <div id="alert" class="alert alert-info alert-dismissible alert-fade custom-alert position-fixed" style="top: -10px; right: 10px; z-index: 1050;" role="alert">
    </div>
}

<div class="text-center">

    <div class="navbar-expand-lg" style="margin-top: 30px">
        <a asp-controller="Television" asp-action="TurnOff">
            <button type="button" class="btn btn-dark">
                Power
            </button>
        </a>
        <a asp-controller="Television" asp-action="TelevisionBroadcast">
            <button type="button" class="btn btn-dark">Television broadcast</button>
        </a>
        <a asp-controller="Television" asp-action="Streaming">
            <button type="button" class="btn btn-dark">Streaming</button>
        </a>
        <a asp-action="Screencast">
            <button type="button" class="btn btn-dark">Screencast</button>
        </a>
        <button id="buttonSave" type="button" class="btn btn-dark">Save</button>
    </div>

    <div class="container mt-5">
        <div class="tv-screen">
            <h4 style="color: white; margin-top: 10px; margin-bottom: 20px; font-size: 25px">@ViewData["Title"]</h4>
            <div class="container mt-5 d-flex align-items-center">
                
                <form class="container" asp-action="EditVolume" method="post">
                    <h5>Edit volume (current volume: @Model.CurrentVolume%): </h5>
                    <input type="text" name="currentView" style="display:none" value="MainMenu">
                    <input name="newVolume" type="range" class="form-range" id="volumeRange" min="0" max="100" value="@Model.CurrentVolume" style="width: 200px; margin-right: 20px; margin-left: 20px; background: #1a1e21">
                    <button type="submit" class="btn btn-dark">Update</button>
                </form>
                
            </div>
            <div class="container mt-5 d-flex justify-content-center align-items-center">
                
                <form asp-action="UpdateSoftware" method="post">
                    <h5>Software version:</h5>
                    <input name="newVersion" type="text" class="form-control" placeholder="@Model.SoftwareVersion" style="width: 200px; margin-right: 20px; margin-left: 20px; background: #1a1e21; color: white">
                    <button class="btn btn-dark" style="margin-top: 15px">Update</button>
                </form>
                
            </div>
            <form asp-action="ChangeResolution" method="post">
                <div class="container mt-5 d-flex justify-content-center align-items-center">
                    <h5>ResolutionX: </h5>
                    <input name="resolutionX" type="number" class="form-control" placeholder="@Model.ResolutionX" style="width: 100px; margin-right: 20px; margin-left: 20px; background: #1a1e21; color: white">
                    <h5>ResolutionY: </h5>
                    <input name="resolutionY" type="number" class="form-control" placeholder="@Model.ResolutionY" style="width: 100px; margin-right: 20px; margin-left: 20px; background: #1a1e21; color: white">
                    <button class="btn btn-dark">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>

TelevisionModelWebApp/Views/Television/Screencast.cshtml
@model TelevisionModelWebApp.Models.ExternalDeviceModel

@{
    ViewData["Title"] = "Screencast";
}
@if (TempData["InfoMessage"] != null)
{
    <div id="alert" class="alert alert-info alert-dismissible alert-fade custom-alert position-fixed" style="top: -10px; right: 10px; z-index: 1050;" role="alert">
        @TempData["InfoMessage"]
        <button type="button" class="close btn btn-close" data-dismiss="alert" aria-label="Close">
        </button>
    </div>
}
else
{
    <div id="alert" class="alert alert-info alert-dismissible alert-fade custom-alert position-fixed" style="top: -10px; right: 10px; z-index: 1050;" role="alert">
    </div>
}

<div class="text-center">

    <div class="navbar-expand-lg" style="margin-top: 30px">
        <a asp-controller="Television" asp-action="TurnOff">
            <button type="button" class="btn btn-dark">Power</button>
        </a>
        <a asp-controller="Television" asp-action="MainMenu">
            <button type="button" class="btn btn-dark">Main menu</button>
        </a>
        <a asp-controller="Television" asp-action="Streaming">
            <button type="button" class="btn btn-dark">Streaming</button>
        </a>
        <a asp-controller="Television" asp-action="TelevisionBroadcast">
            <button type="button" class="btn btn-dark">Television broadcast</button>
        </a>
        <button id="buttonSave" type="button" class="btn btn-dark">Save</button>
    </div>
    <div class="container" style="margin-top: 30px">
        <h5>@ViewData["Title"]</h5>
        @if (Model.Device.Name != "None")
        {
            <p>Connected device: @Model.Device.Name</p>
        }
    </div>
    <div class="container mt-5 d-flex justify-content-center align-items-center" style="margin-top: 30px">
        <form asp-action="Screencast" method="post">
            <div class="container justify-content-center">
                <h5>Connect to a new device:</h5>
                <input name="newDeviceName" type="text" class="form-control" placeholder="@Model.Device.Name" style="width: 200px; margin-right: 20px; margin-left: 20px; background: #1a1e21; color: white">
            </div>
            <div class="container" style="margin-top: 15px">
                <button type="submit" class="btn btn-dark" style="margin: 5px">Connect</button>
                @if (Model.Device.Name != "None")
                {
                    <a asp-controller="Television" asp-action="Disconnect">
                        <button type="button" class="btn btn-danger" style="margin: 5px">Disconnect</button>
                    </a>
                }
            </div>
        </form>
    </div>
    <div class="container mt-5 d-flex align-items-center" style="margin-top: 30px">
        <form class="container" asp-action="EditVolume" method="post">
            <h5>Edit volume (current volume: @Model.Specifications.CurrentVolume%): </h5>
            <input type="text" name="currentView" style="display:none" value="Screencast">
            <input name="newVolume" type="range" class="form-range" id="volumeRange" min="0" max="100" value="@Model.Specifications.CurrentVolume" style="width: 200px; margin-right: 20px; margin-left: 20px; background: #1a1e21">
            <button type="submit" class="btn btn-dark">Update</button>
        </form>
    </div>
</div>

TelevisionModelWebApp/Views/Television/Streaming.cshtml
@model TelevisionModelWebApp.Models.StreamingModel

@{
    ViewData["Title"] = "Streaming";
}
@if (TempData["InfoMessage"] != null)
{
    <div id="alert" class="alert alert-info alert-dismissible alert-fade custom-alert position-fixed" style="top: -10px; right: 10px; z-index: 1050;" role="alert">
        @TempData["InfoMessage"]
        <button type="button" class="close btn btn-close" data-dismiss="alert" aria-label="Close">
        </button>
    </div>
}
else
{
    <div id="alert" class="alert alert-info alert-dismissible alert-fade custom-alert position-fixed" style="top: -10px; right: 10px; z-index: 1050;" role="alert">
    </div>
}

<div class="text-center">

    <div class="navbar-expand-lg" style="margin-top: 30px">
        <a asp-controller="Television" asp-action="TurnOff">
            <button type="button" class="btn btn-dark">Power</button>
        </a>
        <a asp-controller="Television" asp-action="MainMenu">
            <button type="button" class="btn btn-dark">Main menu</button>
        </a>
        <a asp-controller="Television" asp-action="TelevisionBroadcast">
            <button type="button" class="btn btn-dark">Television broadcast</button>
        </a>
        <a asp-action="Screencast">
            <button type="button" class="btn btn-dark">Screencast</button>
        </a>
        <button id="buttonSave" type="button" class="btn btn-dark">Save</button>
    </div>

    <div class="container mt-5">
        <div class="tv-screen">
            <h4 style="color: white; margin-top: 10px; font-size: 25px">@ViewData["Title"]</h4>
            <div class="streaming-container">
                <div class="left">
                    <h5>@Model.Series.Name</h5>
                    <img src="@Model.Series.ImageUrl" alt="Television series image"/>
                    <a href="@Model.Series.Url">
                        <button type="button" class="btn btn-dark left-container-button">Learn more</button>
                    </a>
                </div>
                <div class="right">
                    @Html.Raw(Model.Series.Summary)
                </div>
            </div>
        </div>
    </div>
    <div class="align-content-center">
        <a asp-controller="Television" asp-action="Previous">
            <button type="button" class="btn btn-dark">Previous</button>
        </a>
        <a asp-controller="Television" asp-action="Next">
            <button type="button" class="btn btn-dark">Next</button>
        </a>
    </div>
    <div class="container mt-5 d-flex align-items-center" style="margin-top: 30px">
        <form class="container" asp-action="EditVolume" method="post">
            <h5>Edit volume (current volume: @Model.Specifications.CurrentVolume%): </h5>
            <input type="text" name="currentView" style="display:none" value="Streaming">
            <input name="newVolume" type="range" class="form-range" id="volumeRange" min="0" max="100" value="@Model.Specifications.CurrentVolume" style="width: 200px; margin-right: 20px; margin-left: 20px; background: #1a1e21">
            <button type="submit" class="btn btn-dark">Update</button>
        </form>
    </div>
</div>

TelevisionModelWebApp/Views/Television/TelevisionBroadcast.cshtml
@model TelevisionModelWebApp.Models.BroadcastingModel

@{
    ViewData["Title"] = "Television broadcast";
}
@if (TempData["InfoMessage"] != null)
{
    <div id="alert" class="alert alert-info alert-dismissible alert-fade custom-alert position-fixed" style="top: -10px; right: 10px; z-index: 1050;" role="alert">
        @TempData["InfoMessage"]
        <button type="button" class="close btn btn-close" data-dismiss="alert" aria-label="Close">
        </button>
    </div>
}
else
{
    <div id="alert" class="alert alert-info alert-dismissible alert-fade custom-alert position-fixed" style="top: -10px; right: 10px; z-index: 1050;" role="alert">
    </div>
}

<div class="text-center">

    <div class="navbar-expand-lg" style="margin-top: 30px">
        <a asp-controller="Television" asp-action="TurnOff">
            <button type="button" class="btn btn-dark">Power</button>
        </a>
        <a asp-controller="Television" asp-action="MainMenu">
            <button type="button" class="btn btn-dark">Main menu</button>
        </a>
        <a asp-controller="Television" asp-action="Streaming">
            <button type="button" class="btn btn-dark">Streaming</button>
        </a>
        <a asp-action="Screencast">
            <button type="button" class="btn btn-dark">Screencast</button>
        </a>
        <button id="buttonSave" type="button" class="btn btn-dark">Save</button>
    </div>

    <div class="container mt-5">
        <div class="tv-screen">
            <h4 style="color: white; margin-top: 10px; font-size: 25px">@ViewData["Title"]</h4>
            <p>Channel name: @Model.Channel.Name</p>
            <img src="@Model.Channel.BuildLogoUrl()" alt="Television channel image"/>
        </div>
    </div>
    <div class="align-content-center">
        <a asp-controller="Television" asp-action="Previous">
            <button type="button" class="btn btn-dark">Previous</button>
        </a>
        <a asp-controller="Television" asp-action="Next">
            <button type="button" class="btn btn-dark">Next</button>
        </a>
    </div>
    <div class="container mt-5 d-flex align-items-center" style="margin-top: 30px">
        <form class="container" asp-action="EditVolume" method="post">
            <h5>Edit volume (current volume: @Model.Specifications.CurrentVolume%): </h5>
            <input type="text" name="currentView" style="display:none" value="TelevisionBroadcast">
            <input name="newVolume" type="range" class="form-range" id="volumeRange" min="0" max="100" value="@Model.Specifications.CurrentVolume" style="width: 200px; margin-right: 20px; margin-left: 20px; background: #1a1e21">
            <button type="submit" class="btn btn-dark">Update</button>
        </form>
    </div>
</div>

TelevisionModelWebApp/Views/Television/TurnOff.cshtml
@{
    ViewData["Title"] = "Turned off";
}

<head>
    <title>@ViewData["Title"]</title>
</head>

<div class="text-center">
    
    <div class="navbar-expand-lg" style="margin-top: 30px">
            <a asp-area="" asp-controller="Television" asp-action="TurnOn">
                <button type="button" class="btn btn-dark">
                    Power
                </button>
            </a>
    </div>

    <div class="container mt-5">
            <div class="tv-screen">
            </div>
    </div>
</div>